### ISSUE TITLE
MajdataEdit打开后未响应闪退

### ISSUE THREAD

**Issue by Moying-moe** [LingFeng-bbben/MajdataEdit#1]
私密马赛，刚才issue发到View那个项目去了，重发下。

MajdataEdit打开后，窗口标题显示MainWindow，3、4秒后闪退。
文件夹下已放入maidata.txt和track.mp3。另外如果track.mp3是48000采样的文件，打开MajdataEdit会正常弹窗提示采样率，但是弹窗后仍然闪退。
MajdataView可以正常打开。

已尝试过使用管理员打开，仍闪退。
OS：Windows 10

附测试时使用的maidata.txt内容
```
&title=test
&wholebpm=150
&des_5=testauthor
&artist=testartist
&first_5=0
&lv_5=12
&inote_5=

(150){8}
1,2,3,4,5,6,7,8,
1,2,3,4,5,6,7,8,
1,2,3,4,5,6,7,8,
1,2,3,4,5,6,7,8,
1,2,3,4,5,6,7,8,
1,2,3,4,5,6,7,8,
```

**Comment by LingFeng-bbben** [comment]
把first_5换成first试试

**Comment by Moying-moe** [comment]
> 把first_5换成first试试

改成&first=0了，但是仍然无法打开。

我排查一下是不是我的环境问题。

**Comment by LingFeng-bbben** [comment]
未能复现 排查maidata文件编码和.net framework 4.6.1环境

**Comment by Moying-moe** [comment]
好，有进展会回复这个issue的，辛苦
