### ISSUE TITLE
某种写法双押显示不出来

### ISSUE THREAD

**Issue by xyb314** [LingFeng-bbben/MajdataEdit#10]
写法1显示的是正常的：7/1bw5[8:1],
写法2则会吞掉双押7：1bw5[8:1]/7,
如图所示
![image](https://user-images.githubusercontent.com/77841839/127255575-9e8fdb09-5ad2-4732-ae79-183c3c9fefe0.png)

**Comment by LingFeng-bbben** [comment]
已修复
