### ISSUE TITLE
希望写谱的时候波形能随着光标移动。

### ISSUE THREAD

**Issue by tanetyan** [LingFeng-bbben/MajdataEdit#11]
在按住`ctrl+鼠标左键`或者`ctrl+上下左右`的时候波形会以红色线居中平移。

但是希望在不播放铺面的时候能让黄色箭头居中平移，方便写谱。
![image](https://user-images.githubusercontent.com/88204753/127684990-2d4591fe-5f4e-4142-b365-1a88ae43f6a8.png)

**Comment by LingFeng-bbben** [comment]
没懂 请再详细描述下
