### ISSUE TITLE
数字和逗号分开写的时候，波形图上不会显示tap。

### ISSUE THREAD

**Issue by tanetyan** [LingFeng-bbben/MajdataEdit#12]
如图。
![image](https://user-images.githubusercontent.com/88204753/127685487-68f5280e-881f-4423-b649-6fb8dc04330b.png)
![image](https://user-images.githubusercontent.com/88204753/127685512-0fc94109-bde2-477d-af18-5a8c339832f8.png)

**Comment by LingFeng-bbben** [comment]
已复现

**Comment by LingFeng-bbben** [comment]
已修复 请等待下一个release
