### ISSUE TITLE
铺面编辑器的行间距过大，单页信息量有点少。

### ISSUE THREAD

**Issue by tanetyan** [LingFeng-bbben/MajdataEdit#13]
行间距看起来有一个字高。感觉最多半个字高就够了。或者0.25？
能够显示的情报量有点少。
![image](https://user-images.githubusercontent.com/88204753/127685708-b26fccd2-2a13-4778-92c6-82e8d28e1c03.png)

**Comment by LingFeng-bbben** [comment]
没感觉
