### ISSUE TITLE
自定义快捷键

### ISSUE THREAD

**Issue by tanetyan** [LingFeng-bbben/MajdataEdit#15]
现在播放需要按下`Ctrl+Shift+X或者C`。
对我这种写一小段就要播放好几遍的人来说太需要劳力了。
希望能够有F1 F2 F3 F4的快捷键能一个按键解决。

比如
F1设置起点
F2从起点开始播放/停止播放并跳回播放起点
F3从起点开始播放/停止播放，不跳回播放起点

**Comment by LingFeng-bbben** [comment]
可以理解为自定义快捷键吧

**Comment by LingFeng-bbben** [comment]
Fixed in commit 1280da7.
请期待下一个Release。
