### ISSUE TITLE
播放到音乐结束的时候，按钮不会恢复，但也不处于播放状态

### ISSUE THREAD

**Issue by tanetyan** [LingFeng-bbben/MajdataEdit#16]
音乐播放到结束的时候，调整播放起点不会再次开始播放。
左侧的按钮也没有恢复原状。
![image](https://user-images.githubusercontent.com/88204753/127690923-e4fcd672-18af-4092-9f71-8469251de332.png)

**Comment by LingFeng-bbben** [comment]
其实多按一下就行了
谁想修pull request一下

**Comment by Moying-moe** [comment]
功能比较好实现，但是存在一个问题，如果音频结尾预留的空白过短，播放到最后直接停止，给View发了Stop信号，就会导致All Perfect特效没播完就被掐掉了。尝试了1、2个解决方案但是效果不是很好。
