### ISSUE TITLE
Richtext box 控件在谱面已插入新的文字时不能通过pointer正常定位

### ISSUE THREAD

**Issue by LingFeng-bbben** [LingFeng-bbben/MajdataEdit#19]
复现：
输入1,1,1,1 拖动音频 此时光标正常定位
在1后加入b或x 拖动音频 此时定位出现错误
保存谱面后重启或重新通过SetRawFumenText()方法设定文档内容 错位消失

**Comment by Moying-moe** [comment]
测试后怀疑可能不是b和x而是在处理前对谱面文本进行了Trim的问题，正在定位问题，马上修。
