### ISSUE TITLE
单头多星的星星头颜色问题

### ISSUE THREAD

**Issue by xyb314** [LingFeng-bbben/MajdataEdit#20]
例如1^4[8:1]*^6[8:1],
1星星头应该是蓝色星星头，majdata里好像都是黄色（

**Comment by xyb314** [comment]
补充，如果是有双押，星星头才是黄色，如1^4[8:1]*^6[8:1]/5h[64:1],

**Comment by xyb314** [comment]
补充，绝赞单头多星星星头的图标也错显示为黄色，例如{4}2bw6[8:1],2b>2[8:3]*<2[8:3],
![image](https://user-images.githubusercontent.com/77841839/128336321-2a1db27f-d055-42dd-a4f1-c23444585431.png)

**Comment by LingFeng-bbben** [comment]
同头黄色已修复为蓝色

**Comment by LingFeng-bbben** [comment]
补充部分也已修复
