### ISSUE TITLE
View在低分辨率中容易部分处于屏幕外

### ISSUE THREAD

**Issue by Moying-moe** [LingFeng-bbben/MajdataEdit#31]
由于Edit在启动时默认处于屏幕正中央，而View在被Edit启动时，会被移动到Edit左侧并被放大到相同高度。

此时，如果用户的电脑处于较低的分辨率，亦或是使用了较高的放缩比例，那么View就会有部分位于屏幕外。因此，View被自动移动到Edit一旁的作用就没有了，用户仍然需要重新移动两个窗口的位置。

---

另外，希望能够加入一个选项，可以让View始终吸附在Edit左侧。

**Comment by LingFeng-bbben** [comment]
买个带鱼屏
