### ISSUE TITLE
切换难度后无法正常显示和播放谱面

### ISSUE THREAD

**Issue by Moying-moe** [LingFeng-bbben/MajdataEdit#32]
版本：`Beta1.3`

打开一个已经编写好MASTER难度的谱面文件，在左侧切换至EXPERT谱面，下方时间轴上note正常消失。此时输入EXPERT谱面，时间轴上不出现note，播放则没有内容（直接出现All Perfect）。

此时切换至MASTER难度，谱面正常加载，下方时间轴上note正常出现，可以正常播放。

再次切换回EXPERT难度，发现时间轴上仍然显示着MASTER的谱面，此时无论用哪种方式播放，View中显示的也总是MASTER的谱面。

---

当在EXPERT谱面中退出Edit，下次打开Edit加载该谱面，自动进入EXPERT难度，但是仍然不显示谱面且没有内容播放，切换到MASTER后可以播放，其余和上述情况一致。

---

简单测试发现切换到ADVANCE后的效果和EXPERT一致，其他难度没有测试过。

**Comment by LingFeng-bbben** [comment]
无法复现。切换难度输入note后下方正常显示。
