### ISSUE TITLE
闪退相关

### ISSUE THREAD

**Issue by muvivit** [LingFeng-bbben/MajdataEdit#4]
链接：https://pan.baidu.com/s/1IomVofsN3rnTpXXZN9sDOg 
提取码：link
使用谱面以及歌曲 写谱器也是最新版的

**Comment by LingFeng-bbben** [comment]
打开正常，无法复现。请检查自己的 *.net环境*（.net Framework 4.6.1）
请使用[这里](https://github.com/LingFeng-bbben/MajdataView/releases)的release。
本repo不再发布release。
另：音完全没对齐

**Comment by LingFeng-bbben** [comment]
查明原因为UCEERR_RENDERTHREADFAILURE
强制CPU渲染解决
*RenderOptions.ProcessRenderMode = RenderMode.SoftwareOnly;*
