### ISSUE TITLE
majdata接受的谱面格式与simai语法不匹配

### ISSUE THREAD

**Issue by esterTion** [LingFeng-bbben/MajdataEdit#47]
因为代码仅使用了`Contains`检查关键词，并且没有单note后多余字符检测，所以majdata谱面实际上并不符合simai格式规范
https://github.com/LingFeng-bbben/MajdataEdit/blob/181f70b29861fde60609eef50f5836f5941818ff/SimaiProcess.cs#L464-L483

这导致majdata接受包括但不限于以下note：
（基本都是真实碰到的案例，谱面扔给任何其他转谱器基本都会爆炸）
```
8[8:1]
1-5b
4>6x[2:1]
1vx4[8:1]
2b>5b[8:1]
Ch6[1:1]
```
（暂时想不起来其他了）

**Comment by LingFeng-bbben** [comment]
有空会修，但是欢迎提交pr

**Comment by Moying-moe** [comment]
因为FESTiVAL的新特性，Slide的语法被小程度上的严格化了（至少你不能在结尾随便写b了，因为现在在结尾写b代表BreakSlide）。剩余的部分，需要等有空以后写个新的语法解析器。
