### ISSUE TITLE
发到查看器和Edit内的播放不兼容

### ISSUE THREAD

**Issue by SpadeLushen** [LingFeng-bbben/MajdataEdit#8]
1. 点击播放按钮开始播放，再点击发到查看器，两边会同时停止
2. 点击发到查看器，再点击Edit内的暂停按钮，会停止播放

建议发到查看器时禁用Edit播放暂停按钮，在Edit内播放时禁用发到查看器按钮

**Comment by LingFeng-bbben** [comment]
A5.2已修复
