### ISSUE TITLE
方便写谱时镜像、旋转变换的加功能请求（

### ISSUE THREAD

**Issue by xyb314** [LingFeng-bbben/MajdataEdit#9]
之前为了方便写谱写了个小的辅助工具（，用来镜像什么的
![image](https://user-images.githubusercontent.com/77841839/127156404-a84098ec-4a06-4457-8a35-60626f00776b.png)
不知道可不可以做到编辑器里呀（，就类似选中一段String然后点击某个操作（如左右镜像）就可以在下一行生成对应的结果（类似于Notepad++的Ctrl+D）。
能有快捷键就更好了（溜

**Comment by LingFeng-bbben** [comment]
新版已支持
